version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - openwaba-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=openwaba
      - POSTGRES_USER=openwaba_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_secure_password_here}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - openwaba-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openwaba_user -d openwaba"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_redis_password_here}
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - openwaba-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  openwaba-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
